// @ts-check

/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard"],
  ignoreFiles: ["**/node_modules/**", "**/dist/**"],
  plugins: ["stylelint-use-nesting", "stylelint-order"],
  rules: {
    "color-no-invalid-hex": true,
    "csstools/use-nesting": "always",
    "declaration-empty-line-before": null,
    "declaration-no-important": true,
    "max-nesting-depth": 4,
    "no-descending-specificity": null,
    "no-unknown-animations": true,
    "no-unknown-custom-media": true,
    "no-unknown-custom-properties": true,
    "unit-no-unknown": true,
    "order/properties-order": [
      [
        {
          groupName: "display",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "content",
            "appearance",
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "display",
            "flex",
            "flex-direction",
            "flex-basis",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "align-content",
            "align-items",
            "justify-content",
            "justify-items",
          ],
        },
        {
          groupName: "grid",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "grid",
            "grid-area",
            "grid-template",
            "grid-template-areas",
            "grid-template-rows",
            "grid-template-columns",
            "grid-row",
            "grid-row-start",
            "grid-row-end",
            "grid-column",
            "grid-column-start",
            "grid-column-end",
            "grid-auto-rows",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-gap",
            "grid-row-gap",
            "grid-column-gap",
            "gap",
          ],
        },
        {
          groupName: "dimensions",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "width",
            "max-width",
            "min-width",
            "height",
            "max-height",
            "min-height",
          ],
        },
        {
          groupName: "margin and padding",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
          ],
        },
        {
          groupName: "border and background",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "box-sizing",
            "border",
            "border-top",
            "border-right",
            "border-bottom",
            "border-left",
            "border-width",
            "border-radius",
            "outline",
            "box-shadow",
            "background",
            "background-color",
            "background-image",
          ],
        },
        {
          groupName: "font",
          emptyLineBefore: "always",
          noEmptyLineBetween: true,
          properties: [
            "font",
            "font-family",
            "font-size",
            "font-style",
            "font-weight",
            "font-display",
            "font-smoothing",
            "font-variation-settings",
            "font-optical-sizing",
            "line-height",
            "color",
            "text-decoration",
          ],
        },
      ],
      {
        unspecified: "bottom",
        emptyLineBeforeUnspecified: "always",
      },
    ],
  },
};
